# Generated by Django 2.1.7 on 2019-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor',
            new_name='Brokers',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='Mileage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.AddField(
            model_name='listing',
            name='Year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='Color', max_length=140),
        ),
        migrations.AddField(
            model_name='listing',
            name='drivertrain',
            field=models.CharField(default='FWD', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
